package com.server.enums;

public enum Operation {
    LOGIN,
    REGISTER,
    DISCONNECT,

    UPDATE_PROFILE,

    GET_ALL_ROOMS,
    GET_AVAILABLE_ROOMS,
    ADD_ROOM,
    UPDATE_ROOM,
    DELETE_ROOM,
    CLOSE_ROOM,

    CREATE_RESERVATION,
    CANCEL_RESERVATION,
    GET_MY_RESERVATIONS,
    GET_ALL_RESERVATIONS,
    APPROVE_RESERVATION,

    GET_ALL_EMPLOYEES,
    HIRE_EMPLOYEE,
    FIRE_EMPLOYEE,
    CHANGE_ROLE,

    CHECK_PASSWORD
}
