package com.hotel.common.enums;

public enum Operation {
    LOGIN,
    REGISTER,

    DISCONNECT,

    UPDATE_ACCOUNT,
    GET_ALL_ACCOUNTS,
    GET_ACCOUNT_BY_ID,
    GET_ACCOUNT_BY_EMAIL,

    GET_ALL_ROOMS,
    GET_AVAILABLE_ROOMS,
    ADD_ROOM,
    UPDATE_ROOM,
    DELETE_ROOM,
    CLOSE_ROOM,
    OPEN_ROOM,

    GET_ALL_GUESTS,
    GET_ALL_GUESTS_WITH_RESERVATIONS,

    CREATE_RESERVATION,
    CANCEL_RESERVATION,
    CHECK_OUT,
    GET_MY_RESERVATIONS,
    GET_ALL_RESERVATIONS,
    APPROVE_RESERVATION,

    GET_ALL_EMPLOYEES,
    HIRE_EMPLOYEE,
    FIRE_EMPLOYEE,
    CHANGE_ROLE,
}
